name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      test:
        required: true

  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: script
      run: |
        echo "Test: ${{ github.event.inputs.test }} "
